# 导航目录
nav:
  - 首页: index.md
  - 编程语言:
    - C:
      - 零长数组: code/c语言零长数组理解.md
      - 内存空间分布: code/c语言内存空间分布.md
      - likely()和unlikely()宏: code/c语言likely()和unlikely()宏.md
    - Python:
      - 学习笔记: code/Python学习笔记.md
  - 单片机:
      - 外设:
        - SPI: mcu/spi.md
      - misc:
        - Cortex-M内核学习: misc/Cortex-M内核学习.md
  - ble:
      - 基础概念: ble/BLE基础概念.md 
  - Linux:
      - 进程: linux/D1-进程.md
      - 信号: linux/D2-信号.md
      - 管道: linux/D3-管道.md
      - 消息队列: linux/D4-消息队列.md
      - 共享内存: linux/D5-共享内存.md
      - 线程: linux/D6-线程.md
      - POSIX信号量: linux/D7-POSIX信号量.md
      - POSIX互斥锁: linux/D8-POSIX互斥锁.md
  - 应用笔记:
    - git:
        - 基础操作: git/Git 基础操作.md
        # - 使用笔记: git/Git 使用笔记.md
        - 常见ignore规则: git/gitignore书写规则.md


# 站点信息
site_name: bblog
site_url: https://24849748.github.io/
site_author: bosco
# site_description: 吾尝终日而思矣，不如须臾之所学也。
site_description: bosco's technical notes.
repo_url: https://github.com/24849748/techNote
repo_name: 24849748/techNote
copyright: Copyright &copy; 2024 by bosco.
docs_dir: docs # 文档目录（默认值）
site_dir: site # 网站目录（默认值）
remote_branch: gh-pages # GitHub Pages 远程分支名称（默认值）
remote_name: origin # 远程名称（默认值）
dev_addr: 127.0.0.1:8088 # 预览模式地址（默认值）
use_directory_urls: true # URL 使用目录名还是文件名（默认值）
strict: false # 警告级别（默认值），出现警告就终止程序

# 主题
# theme: readthedocs
# theme: rtd-dropdown

# https://squidfunk.github.io/mkdocs-material/reference/
theme: 
  name: material
  custom_dir: overrides # 覆盖目录
  language: zh    #语言，可设置多套切换
  direction: ltr
  # logo: ./assert/logo.png
  palette:
    # scheme: default # 亮色主题
    scheme: slate # 暗色主题
    # 主题色
    # primary: blue grey
    primary: black
    # primary: brown
    # 强调色
    accent: deep orange
  icon:
    # https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/#logo-icon-bundled
    # logo: https://cdn.jsdelivr.net/gh/24849748/PicBed/ob/20240424232808.png
    # logo: fontawesome/solid/b
    logo: simple/brenntag
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    annotation: material/chevron-right-circle # 注释图标
    admonition: # 提示图标
      # octicons
      # note: octicons/tag-16
      # abstract: octicons/checklist-16
      # info: octicons/info-16
      # tip: octicons/squirrel-16
      # success: octicons/check-16
      # question: octicons/question-16
      # warning: octicons/alert-16
      # failure: octicons/x-circle-16
      # danger: octicons/zap-16
      # bug: octicons/bug-16
      # example: octicons/beaker-16
      # quote: octicons/quote-16
      # FontAwesome
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  features:
    - content.tooltips # 工具提示
    - content.code.annotate # 代码注释
    - content.code.copy # 代码块复制按钮
    - navigation.instant  # 即时加载，页面不会重复加载（已加载页面不会再次加载）
    - navigation.instant.progress ## 进度条
    - navigation.tracking  # 锚点跟踪
    - navigation.tabs  # 导航选项卡
    # - navigation.tabs.sticky  # 导航选项卡粘性
    # - navigation.sections  # 左侧边栏节点是否保持展开
    # - navigation.expand # 侧边栏默认折叠
    - navigation.top  # 返回顶端
    - navigation.footer # 上一页下一页页脚
    - navigation.path # 标题上方显示路径
    # - navigation.indexes
    - search.suggest  # 搜索栏内容建议
    - search.highlight  # 搜索栏内容高亮
    - search.share   # 搜索栏分享按钮
    - header.autohide  # 标题自动隐藏
    - toc.follow # 锚点关注，侧边栏自动滚动，使锚点总是可见
    # - toc.integrate ## 文章目录为左侧导航栏一部分

# 扩展
markdown_extensions:
  # 页面内自动生成目录
  # - toc:
  #     permalink: true

  - toc: # 目录
      marker: "" # 目录替换文本，空字符串则不替换，缺省为 [TOC]
      # title: "" # 目录标题，material 主题会自动根据语言计算
      anchorlink: false # 锚点链接（默认值），给标题自身锚定链接
      permalink: "&para;" # 锚点符号
      permalink_title: "" # 锚点链接提示词，空字符表示没有
      permalink_leading: false # 前置锚点链接（默认值），将锚点放到标题前面
      baselevel: 1 # 最高级别（默认值），往下顺延
      separator: "-" # 分隔符（默认值），替换空格字符
      toc_depth: 4 # 目录显示级别
      slugify:
        !!python/object/apply:pymdownx.slugs.slugify # 锚点链接 URL 格式（小写）
        kwds:
          case: lower

  # 提示
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  # code blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  # formatting
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  # icon emojis 
  # https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  # 图片支持
  - md_in_html
  - pymdownx.blocks.caption

  # 工具提示
  - abbr
  - pymdownx.snippets

  # 列表
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  # katex 支持
  # - pymdownx.arithmatex:
  #     generic: true

plugins:
  - search
  - tags
  # # 统计
  # - statistics:
  #     codelines_per_minute: 10
  #     words_per_minute: 300
#   - social # !需要图像库支持

# extra:
  # generator: false
    # 右下角社交图标
#   social:
#     - icon: fontawesome/brands/github
#       link: https://github.com/24849748

extra_javascript:
  - js/click-colorful.js # 鼠标点击烟花效果
  # - js/background.js # 背景图
  # - js/tablesort.js # 表格排序功能
#   # katex 支持
#   - javascripts/katex.js
#   - https://unpkg.com/katex@0/dist/katex.min.js
#   - https://unpkg.com/katex@0/dist/contrib/auto-render

extra_css:
  # katex 支持
  # - https://unpkg.com/katex@0/dist/katex.min.css
  - css/counter.css # 章节数字编号
  # - css/extra.css # 加载自定义的样式
  - css/background.css # 背景图
